# Generated by Django 3.0.3 on 2020-04-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(error_messages={'required': 'Please provide your email address.', 'unique': ' An account with this email already exists'}, max_length=250, unique=True)),
                ('prn', models.IntegerField()),
                ('st_number', models.IntegerField()),
                ('parent_number', models.IntegerField()),
                ('branch', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('reason', models.CharField(max_length=100, null=True)),
                ('text', models.CharField(max_length=100, null=True)),
                ('depdate', models.CharField(max_length=100, null=True)),
                ('deptime', models.CharField(max_length=100, null=True)),
                ('arrdate', models.CharField(max_length=100, null=True)),
                ('arrtime', models.CharField(max_length=100, null=True)),
                ('parent_number', models.IntegerField()),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.SignUp')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('st_number', models.IntegerField()),
                ('category', models.CharField(max_length=20, null=True)),
                ('problem', models.CharField(max_length=100, null=True)),
                ('room', models.IntegerField()),
                ('user_type', models.CharField(max_length=50, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.SignUp')),
            ],
        ),
    ]
