# Generated by Django 3.0.3 on 2020-04-05 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_college_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signup',
            name='page',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
