# Generated by Django 3.0.3 on 2020-04-05 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0002_auto_20200405_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='is_college_user',
        ),
        migrations.AlterField(
            model_name='signup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
