# Generated by Django 3.0.3 on 2020-04-05 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_auto_20200405_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='student_name',
            new_name='name',
        ),
    ]
